spring:
  data:
    mongodb:
      uri: mongodb://填写mongodb地址/admin
      database: iotkit

  cache:
    cache-names: foo,bar
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=120s

mqtt:
  username: admin
  password: password
  url: tcp://填写mqtt连接地址

  producer:
    #su_mqtt-server-producer-prod
    clientId: 填写mqtt连接clientId见文档中生成clientId说明
    defaultTopic: topic1

  consumer:
    #su_mqtt-server-consumer-prod
    clientId: 填写mqtt连接clientId见文档中生成clientId说明
    defaultTopic: /sys/#

