server:
  port: 8086

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 12MB

  data:
    mongodb:
      uri: mongodb://iotkit:123456@192.168.100.118:27017/?authSource=iotkit
      database: iotkit

  elasticsearch:
    rest:
      uris: http://192.168.100.118:9200
      connection-timeout: 10s

  redis:
    host: 192.168.100.50
    port: 6379
    database: 0
    password: 5tgbNHY^

  cache:
    cache-names: foo,bar
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=300s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

aliyun:
  bucketId: iotkit-images
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI4FmGGouSnScYrGe7rQLA
  accessKeySecret: 9S0xjffwmGW2B3HsE4Efw1TqUy8YXC

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

security:
  oauth2:
    resource:
      filter-order: 3

oauth2:
  auth-server-url: http://127.0.0.1:8086

pulsar:
  broker: pulsar://192.168.100.66:6650
  service: http://192.168.100.66:8080

app:
  systemRole: iot_system_user
  aligenie:
    push:
      device:
mqtt:
  url: tcp:/192.168.100.118:1883

