spring:
  data:
    mongodb:
      uri: mongodb://填写mongodb地址/admin
      database: iotkit

  cache:
    cache-names: foo,bar
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=120s

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

aliyun:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: 填写阿里云accessKeyId
  accessKeySecret: 填写阿里云accessKeySecret

keycloak:
  realm : 填写keycloak中定义的realm
  resource : iotkit
  auth-server-url : 填写keycloak认证地址
  ssl-required : external
  use-resource-role-mappings : false
  cors-max-age : 1000
  cors-allowed-methods : POST PUT DELETE GET
  cors-exposed-headers : WWW-Authenticate
  bearer-only : false
  enable-basic-auth : false
  expose-token : true
  verify-token-audience : false
  connection-pool-size : 20
  disable-trust-manager: true
  allow-any-hostname : false
  token-minimum-time-to-live : 10
  min-time-between-jwks-requests : 10

keycloak-admin-clientid : 填写keycloak中定义的clientId
keycloak-admin-user : 填写keycloak中添加的管理员用户名
keycloak-admin-password : 填写keycloak中添加的管理员密码

app:
  systemRole: iot_system_user

mqtt:
  username: admin
  password: password
  url: tcp://填写mqtt连接地址

  consumer:
    clientId: 填写mqtt连接clientId见文档中生成clientId说明
