spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 12MB

  data:
    mongodb:
      uri: mongodb://填写mongodb地址/admin
      database: iotkit

  elasticsearch:
    rest:
      uris: http://elasticsearch 连接地址
      username: elasticsearch 用户名
      password: 密码
      connection-timeout: 10s

  redis:
    host: redis地址
    port: 6379
    database: 0
    password: redis密码

  cache:
    cache-names: foo,bar
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=120s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

aliyun:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: 填写阿里云accessKeyId
  accessKeySecret: 填写阿里云accessKeySecret

keycloak:
  realm : 填写keycloak中定义的realm
  resource : iotkit
  auth-server-url : 填写keycloak认证地址
  ssl-required : external
  use-resource-role-mappings : false
  cors-max-age : 1000
  cors-allowed-methods : POST PUT DELETE GET
  cors-exposed-headers : WWW-Authenticate
  bearer-only : false
  enable-basic-auth : false
  expose-token : true
  verify-token-audience : false
  connection-pool-size : 20
  disable-trust-manager: true
  allow-any-hostname : false
  token-minimum-time-to-live : 10
  min-time-between-jwks-requests : 10

keycloak-admin-clientid : 填写keycloak中定义的clientId
keycloak-admin-user : 填写keycloak中添加的管理员用户名
keycloak-admin-password : 填写keycloak中添加的管理员密码

pulsar:
  broker: pulsar://pulsar broker地址:6650
  service: http://pulsar 服务地址:8080

app:
  systemRole: iot_system_user

mqtt:
  url: tcp://填写mqtt连接地址

component:
  dir: ./components

gateway:
  function-jar: 填写protocol-function打包的jar存放路径:/xx/xx.jar
